version : "3.9"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  fastify-node-app:
    build: .
    depends_on:
      - fastify-node-mongo

  fastify-node-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db

  fastify-redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - mongo-db:/data/redis

volumes:
  mongo-db: