version : "3.9"
services:
  fastify-node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app:ro
      - /app/node_modules
    env_file:
      - config/dev/.env
    command: npm run start-dev

  fastify-node-mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root