version : "3.9"
services:
  fastify-node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - fastify-node-mongo

  fastify-node-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-db:/data/db

  fastify-redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - mongo-db:/data/redis

volumes:
  mongo-db: